---
title: "Untitled"
author: "Felix Pichardo"
date: "2024-09-18"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(here)
  library(foreign)
  library(dplyr) #for %>%
  library(tidyr)
  library(plyr)   #for revalue
  library(ggplot2)
  library(gridExtra)
  library(grid)   #for textGrob
  library(kableExtra) #for knitr tables
  library(caret)
  library(MplusAutomation)
  library(tidyverse)
  library(psych)
  library(car)
  library(corrplot)
  library(lme4)
  library(lmerTest)  # For p-values in mixed models
})

# Directories
PROJ_DIR            = file.path(here::here())
DATA_DIR            = file.path(PROJ_DIR, "Data")
SAFE_DATA_DIR       = file.path(DATA_DIR, "AHRB")
MODELS_DIR          = file.path(PROJ_DIR, "models")
MODELS_RDS_DIR      = file.path(MODELS_DIR, "rds")
MODELS_RDS_FIT_DIR  = file.path(MODELS_RDS_DIR, "fit")
MODELS_RDS_PoPC_DIR = file.path(MODELS_RDS_DIR, "postpc")

# Source helper functions
source(file.path(PROJ_DIR, "scripts", "helpers", "helper_functions_cmdSR.R"))

# Set model info
main_model_name = "pvldelta"
task <- "igt_mod" #opt$task
group_type <- "batch_001"

model_defaults = get_model_defaults(task)

# Load Data
## Trial-level data
wave1.sav.file = file.path(SAFE_DATA_DIR, "modigt_data_Wave1.sav")
wave1.raw      = read.spss(wave1.sav.file,to.data.frame = TRUE)

efa.sample.file = file.path(SAFE_DATA_DIR, "efa_sample.csv")
efa.sample.data = read.csv(efa.sample.file)

# Excluded subs
exclude_file = file.path(SAFE_DATA_DIR, "subs/subject_ids_excludes.txt")
excluded_sids = unlist(unname(read.csv(exclude_file, header = F)))

## Risk  data
risk.file = file.path(SAFE_DATA_DIR, "AHRB.P1W1_v11_AW_v2.sav")
risk.data = read.spss(risk.file,to.data.frame = TRUE)

# Convert pubertyage to numeric
convert_pubertyage <- function(puberty_cat) {
  # Convert categorical pubertyage to numeric values
  # Using midpoints or conservative estimates for ranges
  case_when(
    puberty_cat == "=/< 10" ~ 10,    # Using upper bound of 10
    puberty_cat == "11" ~ 11,
    puberty_cat == "12" ~ 12,
    puberty_cat == "13" ~ 13,
    puberty_cat == "14" ~ 14,
    puberty_cat == "15" ~ 15,
    puberty_cat == "16" ~ 16,
    puberty_cat == "=/> 17" ~ 17,    # Using lower bound of 17
    TRUE ~ NA_real_                  # Handle any other cases
  )
}

# Apply conversion and calculate time since puberty
create_puberty_metrics <- function(df) {
  df %>%
    mutate(
      pubertyage_num = convert_pubertyage(pubertyage),
      time_since_puberty = age - pubertyage_num
    )
}

# Apply to the dataframes
risk.data <- risk.data %>% create_puberty_metrics()


variable_names = tolower(c("BISB", "BSSS_ES", "BSSS_BS", "BSSS_TS", "BSSS_SD", 
                   "ysr_attentionproblems", "ysr_rulebreak", "ysr_mrulebreak", "ysr_aggressive", "ysr_maggressive", "ysr_conduct", "ysr_mconduct_", "age", "time_since_puberty",
                   "SID"))

risk.data$pubertaltiming <- factor(risk.data$pubertaltiming, 
                                   levels = c("much earlier", "earlier", 
                                              "at the same time", "later", 
                                              "much later"), 
                                   ordered = TRUE)

risk.data$pubertaltiming_num = as.numeric(risk.data$pubertaltiming)
```


# RL-Only
```{r}
model_name <- main_model_name

if (grepl("batch", group_type)){
  fit_model_name = paste(task, group_type, model_name, sep="_")
  full_model_name = paste(task, "sing", model_name, sep="_")
} else {
  fit_model_name = paste(task, group_type, model_name, sep="_")
  full_model_name = paste(task, group_type, model_name, sep="_")
}


model.fit.path = file.path(MODELS_RDS_FIT_DIR, paste0(fit_model_name, "_fit.rds"))
rds_pathname  = model.fit.path

sample_df = wave1.raw
```


### Load fit
```{r}
fit_output_file = sub('models', file.path('Data', task), paste0("/", tools::file_path_sans_ext(rds_pathname), "_output.rds"))

model_fit_obj = readRDS(file = fit_output_file)
```

## Extract parameters
```{r}
sids = unname(unlist(lapply(model_fit_obj, function(x) x$subid)))
sids = sids[!unlist(lapply(sids, function(x) x %in% as.character(excluded_sids)))]

# Create a data frame to store the parameters
param_df <- data.frame(
  sid = sids
)

for (param in model_defaults[[full_model_name]]$params){
  param_df[[param]] <- numeric(length(sids))
}

for (sid_idx in 1:length(sids)) {
  for (param in model_defaults[[full_model_name]]$params) {
      param_df[[param]][sid_idx] <- model_fit_obj[[sid_idx]]$summary_stats$mean[which(model_fit_obj[[sid_idx]]$all_params == param)]
  }
}


merged_df <- merge(param_df, risk.data[variable_names], by = "sid")

final_df <- merge(merged_df, risk.data[c("sid", "bsss8", "male", "race_ethnicity", "grade12", "parent_edu6")], by = "sid")

final_df = wave1.raw %>% 
  group_by(sid) %>% 
  dplyr::select(grpid, v_groupnumber, schoolid, districtid) %>% 
  ungroup() %>% 
  unique() %>% 
  right_join(final_df, by = "sid")
```

## Correlation
```{r}
relevant_data = final_df[names(final_df)[unlist(lapply(final_df, is.numeric))]]

corr = cor(relevant_data, use = "complete.obs")
corrplot::corrplot(corr, diag = F, type = "upper")
```

## LM
```{r}
lm_results <- lapply(model_defaults[[full_model_name]]$params, function(param) {
  formula <- as.formula(paste("bsss_sd ~", param))
  lm(formula, data = final_df)
})

# Print summaries
lapply(lm_results, summary)
```

```{r}
lm_results <- lapply(model_defaults[[full_model_name]]$params, function(param) {
  formula <- as.formula(paste("ysr_attentionproblems ~", param))
  lm(formula, data = final_df)
})

# Print summaries
lapply(lm_results, summary)
```

```{r}
lm_results <- lapply(model_defaults[[full_model_name]]$params, function(param) {
  formula <- as.formula(paste("ysr_maggressive_t ~", param))
  lm(formula, data = final_df)
})

# Print summaries
lapply(lm_results, summary)
```

```{r}
lm_results <- lapply(model_defaults[[full_model_name]]$params, function(param) {
  formula <- as.formula(paste("ysr_mconduct_t ~", param))
  lm(formula, data = final_df)
})

# Print summaries
lapply(lm_results, summary)
```

## LMER

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste(param, "~ grade12 + (1|schoolid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste(param, "~ time_since_puberty + (1|schoolid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```


```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste(param, " ~ time_since_puberty + age + (1|schoolid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("bsss_sd ~", param, "+ (1|schoolid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```


```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_attentionproblems ~", param, "+ (1|schoolid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_maggressive_t ~", param, "+ (1|schoolid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```


```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_mconduct_t ~", param, "+ (1|schoolid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

### Test Controls
#### Gender 
```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("bsss_sd ~", param, "*male + (1|schoolid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_attentionproblems ~", param, "*male + (1|schoolid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_maggressive_t ~", param, "*male + (1|schoolid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_mconduct_t ~", param, "*male + (1|schoolid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

#### Grade

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("bsss_sd ~", param, "*grade12 + (1|grpid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_attentionproblems ~", param, "*grade12 + (1|grpid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_maggressive_t ~", param, "*grade12 + (1|grpid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_mconduct_t ~", param, "*grade12 + (1|grpid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

#### Eth
```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("bsss_sd ~", param, "*race_ethnicity + (1|grpid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_attentionproblems ~", param, "*race_ethnicity + (1|grpid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_maggressive_t ~", param, "*race_ethnicity + (1|grpid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_mconduct_t ~", param, "*race_ethnicity + (1|grpid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```


#### PEdu
```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("bsss_sd ~", param, "*parent_edu6 + (1|grpid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_attentionproblems ~", param, "*parent_edu6 + (1|grpid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_maggressive_t ~", param, "*parent_edu6 + (1|grpid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_mconduct_t ~", param, "*parent_edu6 + (1|grpid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```


### Controls
```{r}
final_df$race_ethnicity_ANH = as.numeric(final_df$race_ethnicity == "asian non hispanic")

# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("bsss_sd ~", param, "*male + race_ethnicity_ANH + (1|grpid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```


```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_attentionproblems ~", param, "*male + race_ethnicity_ANH + (1|grpid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_maggressive_t ~", param, "*male + race_ethnicity_ANH + (1|grpid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_mconduct_t ~", param, "*male + race_ethnicity_ANH + (1|grpid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

### Interactions
```{r}
# Run models for each parameter
formula <- as.formula(paste("bsss_sd ~ gain + loss + male + grade12 + v_groupnumber + (1|grpid)"))
model <- lmer(formula, data = final_df)
lmer_results <- summary(model)

# Print results
print(lmer_results)
```


```{r}
# Run models for each parameter
formula <- as.formula(paste("ysr_attentionproblems ~ gain + loss + male + grade12 + v_groupnumber + (1|grpid)"))
model <- lmer(formula, data = final_df)
lmer_results <- summary(model)

# Print results
print(lmer_results)
```

```{r}
# Run models for each parameter
formula <- as.formula(paste("ysr_maggressive_t ~ gain + loss + male + grade12 + v_groupnumber + (1|grpid)"))
model <- lmer(formula, data = final_df)
lmer_results <- summary(model)

# Print results
print(lmer_results)
```

```{r}
# Run models for each parameter
formula <- as.formula(paste("bsss_ts ~ gain + (1|schoolid)"))
model <- lmer(formula, data = hybrid_final_df)
lmer_results <- summary(model)

# Print results
print(lmer_results)
```






















# Hybrid
```{r}
model_name <- paste0(main_model_name, "_ddm_b1b")

if (grepl("batch", group_type)){
  fit_model_name = paste(task, group_type, model_name, sep="_")
  full_model_name = paste(task, "sing", model_name, sep="_")
} else {
  fit_model_name = paste(task, group_type, model_name, sep="_")
  full_model_name = paste(task, group_type, model_name, sep="_")
}


model.fit.path = file.path(MODELS_RDS_FIT_DIR, paste0(fit_model_name, "_fit.rds"))
rds_pathname  = model.fit.path

sample_df = wave1.raw
```


### Load fit
```{r}
fit_output_file = sub('/models/', '/Data/', paste0(tools::file_path_sans_ext(rds_pathname), "_output.rds"))

model_fit_obj = readRDS(file = fit_output_file)
```

## Extract parameters
```{r}
sids = unname(unlist(lapply(model_fit_obj, function(x) x$subid)))

# Create a data frame to store the parameters
param_df <- data.frame(
  sid = sids
)

for (param in model_defaults[[full_model_name]]$params){
  param_df[[param]] <- numeric(length(sids))
}

for (sid_idx in 1:length(sids)) {
  for (param in model_defaults[[full_model_name]]$params) {
      param_df[[param]][sid_idx] <- model_fit_obj[[sid_idx]]$summary_stats$median[which(model_fit_obj[[sid_idx]]$all_params == param)]
  }
}


final_df <- merge(param_df, risk.data[variable_names], by = "sid")

final_df <- merge(final_df, risk.data[c("sid", "bsss8", "male", "race_ethnicity", "grade12", "parent_edu6")], by = "sid")

final_df = wave1.raw %>% 
  group_by(sid) %>% 
  dplyr::select(grpid, schoolid, districtid) %>% 
  ungroup() %>% 
  unique() %>% 
  right_join(final_df, by = "sid")
```

## Correlation
```{r}
relevant_data = final_df[names(final_df)[unlist(lapply(final_df, is.numeric))]]

corr = cor(relevant_data, use = "complete.obs")
corrplot::corrplot(corr, diag = F, type = "upper")
```

## LM
```{r}
lm_results <- lapply(model_defaults[[full_model_name]]$params, function(param) {
  formula <- as.formula(paste("bsss_sd ~", param))
  lm(formula, data = final_df)
})

# Print summaries
lapply(lm_results, summary)
```

```{r}
lm_results <- lapply(model_defaults[[full_model_name]]$params, function(param) {
  formula <- as.formula(paste("ysr_attentionproblems ~", param))
  lm(formula, data = final_df)
})

# Print summaries
lapply(lm_results, summary)
```

```{r}
lm_results <- lapply(model_defaults[[full_model_name]]$params, function(param) {
  formula <- as.formula(paste("ysr_maggressive_t ~", param))
  lm(formula, data = final_df)
})

# Print summaries
lapply(lm_results, summary)
```


```{r}
lm_results <- lapply(model_defaults[[full_model_name]]$params, function(param) {
  formula <- as.formula(paste("ysr_mconduct_t ~", param))
  lm(formula, data = final_df)
})

# Print summaries
lapply(lm_results, summary)
```

## LMER
```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("age ~", param, "+ (1|schoolid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("pubertaltiming_num ~", param, "+ (1|schoolid)"))
  model <- lmer(formula, data = hybrid_final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```


```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste(param, " ~ pubertaltiming_num + age + (1|grpid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("bsss_sd ~", param, "+ (1|grpid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```


```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_attentionproblems ~", param, "+ (1|schoolid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_maggressive_t ~", param, "+ (1|schoolid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```


```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_mconduct_t ~", param, "+ (1|schoolid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

### Test Controls
#### Gender 
```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("bsss_sd ~", param, "*male + (1|schoolid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_attentionproblems ~", param, "*male + (1|schoolid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_maggressive_t ~", param, "*male + (1|schoolid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_mconduct_t ~", param, "*male + (1|schoolid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

#### Grade

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("bsss_sd ~", param, "*grade12 + (1|schoolid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_attentionproblems ~", param, "*grade12 + (1|schoolid)"))
  model <- lmer(formula, data = hybrid_final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_maggressive_t ~", param, "*grade12 + (1|schoolid)"))
  model <- lmer(formula, data = hybrid_final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_mconduct_t ~", param, "*grade12 + (1|schoolid)"))
  model <- lmer(formula, data = hybrid_final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

#### Eth
```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("bsss_sd ~", param, "*race_ethnicity + (1|grpid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_attentionproblems ~", param, "*race_ethnicity + (1|grpid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_maggressive_t ~", param, "*race_ethnicity + (1|grpid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_mconduct_t ~", param, "*race_ethnicity + (1|grpid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```


#### PEdu
```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("bsss_sd ~", param, "*parent_edu6 + (1|grpid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_attentionproblems ~", param, "*parent_edu6 + (1|grpid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_maggressive_t ~", param, "*parent_edu6 + (1|grpid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_mconduct_t ~", param, "*parent_edu6 + (1|grpid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```


### Controls
```{r}
hybrid_final_df$race_ethnicity_ANH = as.numeric(hybrid_final_df$race_ethnicity == "asian non hispanic")

# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("bsss_sd ~", param, "*male + race_ethnicity_ANH + grade12 + (1|schoolid)"))
  model <- lmer(formula, data = hybrid_final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```


```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_attentionproblems ~", param, "*male + race_ethnicity_ANH + grade12 + (1|schoolid)"))
  model <- lmer(formula, data = hybrid_final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_maggressive_t ~", param, "*male + race_ethnicity_ANH + grade12 + (1|schoolid)"))
  model <- lmer(formula, data = hybrid_final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_mconduct_t ~", param, "*male + race_ethnicity_ANH + grade12 + (1|schoolid)"))
  model <- lmer(formula, data = hybrid_final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply(model_defaults[[full_model_name]]$params, run_lmer)

# Print results
print(lmer_results)
```

### Interactions
```{r}
# Run models for each parameter
formula <- as.formula(paste("ysr_aggressive ~ male + grade12 +
                            (1|schoolid)"))
model <- lmer(formula, data = rl_final_df)
lmer_results <- summary(model)

# Print results
print(lmer_results)
```



```{r}
# Run models for each parameter
formula <- as.formula(paste("ysr_mconduct_t ~ boundary1 + boundary + beta + tau + drift_con + (gain + loss)*male + grade12 + time_since_puberty + update +  (1|schoolid)"))
model <- lmer(formula, data = final_df)
lmer_results <- summary(model)

# Print results
print(lmer_results)
```


```{r}
# Run models for each parameter
formula <- as.formula(paste("ysr_attentionproblems ~ boundary + beta + tau + gain + loss + male + age + (1|schoolid)"))
model <- lmer(formula, data = hybrid_final_df)
lmer_results <- summary(model)

# Print results
print(lmer_results)
```

```{r}
# Run models for each parameter
formula <- as.formula(paste("ysr_maggressive_t ~ boundary + beta + tau + gain + loss + male + age + (1|schoolid)"))
model <- lmer(formula, data = hybrid_final_df)
lmer_results <- summary(model)

# Print results
print(lmer_results)
```

```{r}
# Run models for each parameter
formula <- as.formula(paste("ysr_mconduct_t ~ boundary + beta + tau + gain + loss + male + age + (1|schoolid)"))
model <- lmer(formula, data = hybrid_final_df)
lmer_results <- summary(model)

# Print results
print(lmer_results)
```







```{r}
# Run models for each parameter
formula <- as.formula(paste("good_play_ratio ~ boundary + beta + tau + gain + loss + male + age + (1|schoolid)"))
model <- lmer(formula, data = hybrid_final_df)
lmer_results <- summary(model)

# Print results
print(lmer_results)
```








```{r}
# Function to run lmer for each parameter
run_lmer <- function(param) {
  formula <- as.formula(paste("ysr_mconduct_t ~", param, "+ (1|schoolid + districtid)"))
  model <- lmer(formula, data = final_df)
  return(summary(model))
}

# Run models for each parameter
lmer_results <- lapply("gain + loss", run_lmer)

# Print results
print(lmer_results)
```


