name: "ev"
description: "Expected Value Model"
task: "igt_mod"
response_type: "choice"

parameters:
  con:
    range: [-5, 5]
    transform: "logistic"
    prior: "normal(0, 1)"
  
  wgt_pun:
    range: [0, 1]
    transform: "logistic"
    prior: "normal(0, 1)"
  
  wgt_rew:
    range: [0, 1]
    transform: "logistic"
    prior: "normal(0, 1)"
  
  update:
    range: [0, 1]
    transform: "logistic"
    prior: "normal(0, 1)"
