name: "igt_mod"
description: "Modified Iowa Gambling Task"

deck_properties:
  A:
    gain: 100
    loss: -250
    prob_gain: 0.50
    prob_loss: 0.50
    prob_zero: 0.00
    first_loss: 3
    expected_value: 25
  B:
    gain: 100
    loss: -1150
    prob_gain: 0.90
    prob_loss: 0.10
    prob_zero: 0.00
    first_loss: 10
    expected_value: 25
  C:
    gain: 50
    loss: -25
    prob_gain: 0.50
    prob_loss: 0.25
    prob_zero: 0.25
    first_loss: 13
    expected_value: 18.75
  D:
    gain: 50
    loss: -200
    prob_gain: 0.90
    prob_loss: 0.10
    prob_zero: 0.00
    first_loss: 10
    expected_value: 25

training:
  decks: [4, 3, 2, 3, 3, 2, 2, 4, 2, 1, 4, 1, 4, 3, 2, 4, 3, 1, 1, 1]
  choices: [1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0]

defaults:
  n_blocks: 6
  trials_per_block: 20
