parameters:
  Arew:
    range: [0, 1]
    prior: normal(0, 1)
    categories:
      low: [0, 0.3]
      medium: [0.3, 0.7]
      high: [0.7, 1]
  Apun:
    range: [0, 1]
    prior: normal(0, 1)
    categories:
      low: [0, 0.3]
      medium: [0.3, 0.7]
      high: [0.7, 1]
  K:
    range: [0, 5]
    prior: normal(0, 1)
    categories:
      low: [0, 1.5]
      medium: [1.5, 3.5]
      high: [3.5, 5]
  betaF:
    range: [-5, 5]
    prior: normal(0, 1)
    categories:
      low: [-5, -1.7]
      medium: [-1.7, 1.7]
      high: [1.7, 5]
  betaP:
    range: [-5, 5]
    prior: normal(0, 1)
    categories:
      low: [-5, -1.7]
      medium: [-1.7, 1.7]
      high: [1.7, 5]