name: "ev_ddm"
description: "Expected Value and DDM Model"
task: "igt_mod"
response_type: "choice_rt"

parameters:
  boundary:
    range: [0, inf]
    transform: "exp"
    prior: "normal(0, 1)"
    
  tau:
    range: [RTbound, minRT]
    transform: "logistic_scale"
    prior: "normal(0, 1)"
    
  beta:
    range: [0, 1]
    transform: "logistic_scale"
    prior: "normal(0, 1)"
    
  drift_con:
    range: [-5, 5]
    transform: "logistic_scale"
    prior: "normal(0, 1)"
  
  wgt_pun:
    range: [0, 1]
    transform: "logistic"
    prior: "normal(0, 1)"
  
  wgt_rew:
    range: [0, 1]
    transform: "logistic"
    prior: "normal(0, 1)"
  
  update:
    range: [0, 1]
    transform: "logistic"
    prior: "normal(0, 1)"
