name: "pulvppdecayg_ddm"
description: "Prospect Utility Learning Model with VPP, Decay, and DDM"
task: "igt_mod"
response_type: "choice_rt"

parameters:
  boundary:
    range: [0, Inf]
    transform: "exp"
    prior: "normal(0, 1)"
  
  tau:
    range: [0.1, 0.9]
    transform: "none"
    prior: "normal(0, 1)"
  
  beta:
    range: [0, 1]
    transform: "logistic"
    prior: "normal(0, 1)"
  
  drift_con:
    range: [-5, 5]
    transform: "none"
    prior: "normal(1, 1)"

  gain:
    range: [0, 10]
    transform: "none"
    prior: "normal(1, 0.5)"
  
  loss:
    range: [0, 10]
    transform: "none"
    prior: "normal(1, 1)"
    
  mag:
    range: [0, 2]
    transform: "none"
    prior: "normal(1, 0.5)"
    
  decay:
    range: [0, 1]
    transform: "logistic"
    prior: "normal(0, 1)"
  
  k:
    range: [0, 1]
    transform: "logistic"
    prior: "normal(0, 1)"
  
  w:
    range: [0, 1]
    transform: "logistic" 
    prior: "normal(0, 1)"
  
  ep:
    range: [-Inf, Inf]
    transform: "none"
    prior: "normal(0, 1)"
