name: "pvldecay_tic"
description: "Prospect Valence Learning Model with Decay Update and Trial-Independent Consistency"
task: "igt_mod"
response_type: "choice"

parameters:
  gain:
    range: [0, 2]
    transform: "none"
    prior: "normal(1, 0.5)"
  
  loss:
    range: [0, 10]
    transform: "none"
    prior: "normal(1, 1)"
  
  con:
    range: [0, 5]
    transform: "none"
    prior: "normal(1, 1)"

  decay:
    range: [0, 1]
    transform: "logistic"
    prior: "normal(0, 1)"
